In [ ]:
# Mathematical Machine Learning - Tutorial 1

In [8]:
import numpy as np 
from scipy.linalg import lu, lu_solve, lu_factor, cho_factor, cho_solve

In [2]:
a=np.array([1,1,0])
b=np.array([-1,2,5])
M=np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])

## a) Inner Product

In [3]:
print(np.inner(a,b))

1


## b) Matrix-Vector Product

In [5]:
print(M @ b)

[-4  0  8]


## c) $l_2$ Norm

In [7]:
print(np.linalg.norm(b,ord=None))

5.477225575051661


## d) Solve via LU

In [15]:
lu_fac = lu_factor(M)
x_lu = lu_solve(lu_fac, b)
print(x_lu)

[1.5 4.  4.5]


## e) Solve via Cholesky

In [16]:
L_chol = np.linalg.cholesky(M)

# forward substitution
y_chol = np.linalg.solve(L_chol, b)

# bachward substitution
x_chol = np.linalg.solve(L_chol.T, y_chol)

print("x =", x_chol)
    

x = [1.5 4.  4.5]


In [14]:
print(np.abs(x_lu - x_chol))

[2.22044605e-16 1.33226763e-15 8.88178420e-16]
